name: observable_roles
version: 0.1.3
description: >
  An implementation of Observable pattern that also
  supports queueing of events and roles for publishers.

author: Roman Snitko <roman.snitko@gmail.com>
homepage: https://github.com/snitko/dart-observable_roles
  
dev_dependencies:
  test: '>=0.12.0'
